trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        containerRegistry: 'Shilpa-exto-dockerhub' 

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: 'Shilpa-exto-dockerhub' 

    - task: Docker@2
      displayName: Push the image to Docker Hub
      inputs:
        command: push
        containerRegistry: 'Shilpa-exto-dockerhub' 
        repository: 'shilpasunakar/shilpawebappgaea'
        tags: |
          $(tag)
