trigger:
- master

resources:
- repo: self

variables:
  # Define a custom tag based on the build ID or any other desired method.
  customTag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'shilpasunakar/shilpawebappgaea:$(customTag)'
        containerRegistry: 'Shilpa-exto-dockerhub' 

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: 'login'
        containerRegistry: 'Shilpa-exto-dockerhub'

    - task: Docker@2
      displayName: Push the image to Docker Hub
      inputs:
        command: 'push'
        containerRegistry: 'Shilpa-exto-dockerhub'
        repository: 'shilpasunakar/shilpawebappgaea'
        tags: 'shilpasunakar/shilpawebappgaea:$(customTag)'
